# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self
 

variables:
  tag: '$(Build.BuildId)'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'  

stages:

- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    variables:
      buildTime: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]
    steps: 
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: echo build image is $buildTime      
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '--configuration $(buildConfiguration)'
        projects: '**/vincall.service.csproj'       
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true  
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.ArtifactStagingDirectory)'
        Contents: '**'
        TargetFolder: './release' 
#    - task: Docker@2
#      displayName: Build an image
#      inputs:
#        command: build
#        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
#        tags: |
#          $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'register'
        repository: 'x2/vincallservice/test-vincall'
        tags: |
          $(buildTime)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'