// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Vincall.Infrastructure
{
    public partial class CallList
    {
        public int Id { get; set; }
        public string ExtensionNumber { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public int? CallTime { get; set; }
        public DateTime CreateDate { get; set; }
    }
}