// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Vincall.Infrastructure
{
    public partial class Setting
    {
        public int Id { get; set; }
        public string OptionKey { get; set; }
        public string OptionValue { get; set; }
        public int? Type { get; set; }
    }
}