// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;


namespace Vincall.Infrastructure
{
    public partial class SysVersion
    {
        public int Id { get; set; }
        public string Version { get; set; }
        public string Desc { get; set; }
        public DateTime? CreateDate { get; set; }
    }
}