// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Vincall.Infrastructure
{
    public partial class TwilioSetting
    {
        public int Id { get; set; }
        public string CallId { get; set; }
        public string AccountSid { get; set; }
        public string AuthToken { get; set; }
        public string AppSid { get; set; }
        public string ApiSid { get; set; }
        public string ApiSecret { get; set; }
    }
}