// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Vincall.Infrastructure
{
    public partial class User
    {
        public int Id { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public string Remark { get; set; }
        public DateTime? CreateDate { get; set; }
        public bool IsAdmin { get; set; }

        public long TenantId { get; set; }
        public string Email { get; set; }

    }
}